# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
author: Marek Piechut
title: Marek Piechut
email: marek.piechut@gmail.com
description: >
  Software dev messing with hardware & electronics. Posting on microservices, databases, programming languages and weird keyboards.
  Founder @dayonepl. Creator of "Po Prostu JS" podcast. Now building custom keyboards.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://marekpiechut.github.io" # the base hostname & protocol for your site
twitter_username: marekpiechut
github_username:  marekpiechut

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
