---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments


### content configuration ###
title:       "Marek Piechut - projects and postings"
keywords:    "marek, piechut, programming, development, javascript, js, java, node, nodejs, safari, osx, mac, translation, translate, extension, browser, translateme"
description: "Marek Piechut - projects and postings"
source_link: "https://github.com/marekpiechut"
favicon:     
touch_icon:  
google_analytics_key: UA-59185106-1


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#fff'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
